export * from './Behavior'
export { registerBehavior, getBehaviorClass, getRegisteredTypes } from './registry'
export * from './NodBehavior'
export * from './StillnessBehavior'
export * from './EyeBehavior'
export * from './SpeechBehavior'
export * from './TypeBehavior'
export * from './RelaxJawBehavior'
export * from './TongueOutBehavior'
export * from './DirectionalGazeBehavior'
export * from './FormBehavior'
export * from './MotionBehavior'
export * from './ImpactBehavior'
